language: python
cache: pip
python:
    - 3.6
install:
    - pip install --upgrade pip
    - pip install flake8
    - python setup.py develop
    - pip install gitpython nltk  # needed for some tests
    - pip install regex scipy scikit-learn pexpect  # tfidf-retriever dependencies
    - pip install sphinx sphinx_rtd_theme  # doc generation
    # install pytorch non-cuda version
    - pip install torch torchvision --progress-bar off
    # Install mturk deps
    - pip install boto3 botocore joblib websocket sh websocket_server
script:
    - ./tests/lint_changed.sh
    - python setup.py test -s tests.suites.travis -q
notifications:
    on_success: change
    on_failure: always
