language: python
cache: pip
python:
    - 3.6
install:
    - pip install flake8
    - python setup.py develop
    - pip install regex scipy sklearn pexpect  # tfidf-retriever dependencies
    # install pytorch non-cuda version
    - pip install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-linux_x86_64.whl
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - time flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
    - python tests/test_import.py
    - python tests/test_init.py
    - python tests/test_tasklist.py
    - python tests/test_dict.py
    - python tests/test_display_data.py
    - python tests/test_utils.py
    - python tests/test_threadutils.py
    - python tests/test_torch_agent.py
    - python tests/test_eval_model.py
    - python tests/test_hogwild.py
    - python tests/test_train_model.py
    - python tests/test_tfidf_retriever.py
notifications:
    on_success: change
    on_failure: always
