name: conda_parlai
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - altair=4.1.0=py_1
  - entrypoints=0.3=py37hc8dfbb8_1002
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jsonschema=3.2.0=py_2
  - markupsafe=1.1.1=py37hb5d75c8_2
  - pyrsistent=0.17.3=py37h8f50634_1
  - python_abi=3.7=1_cp37m
  - toolz=0.11.1=py_0
  - vega_datasets=0.8.0=py_0
  - zipp=3.3.1=py_0
  - _libgcc_mutex=0.1=main
  - attrs=19.3.0=py_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h7b6447c_1000
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.14.3=py37he30daa8_0
  - chardet=3.0.4=py37_1003
  - cryptography=3.1.1=py37h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - docutils=0.16=py37_1
  - freetype=2.9.1=h8a8886c_1
  - idna=2.10=py_0
  - intel-openmp=2020.1=217
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py_0
  - openssl=1.1.1h=h7b6447c_0
  - pandas=1.1.0=py37he6710b0_0
  - pillow=7.1.2=py37hb39fc2d_0
  - pip=20.0.2=py37_3
  - pycparser=2.20=py_2
  - pyopenssl=19.1.0=py_1
  - pysocks=1.7.1=py37_1
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - setuptools=46.4.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.8=hbc83047_0
  - tqdm=4.50.2=py_0
  - urllib3=1.25.10=py_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pytorch=1.6.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - torchtext=0.7.0=py37
  - torchvision=0.7.0=py37_cu101
prefix: /private/home/<your-username>/.conda/envs/conda_parlai

